"""add donation claim fields

Revision ID: 7db5786609fe
Revises: 97e02b19b637
Create Date: 2026-09-22 15:49:12.400756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db5786609fe'
down_revision = '97e02b19b637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['claimed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_donations', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed_by')

    # ### end Alembic commands ###
